name: Run Cypress Tests

# Disparadores del flujo de trabajo
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    # Usar diferentes versiones de Node si es necesario
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Paso 2: Configurar Node.js en la versión especificada
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Paso 3: Instalar dependencias del proyecto
      - name: Install dependencies
        run: |
          npm install
          npm install --save-dev cypress  # Instalar Cypress como devDependency

      # Paso 4: Iniciar el servidor Expo o React Native Web
      - name: Start Expo (or React Native Web) server
        run: |
          npx expo-cli start --web --non-interactive &
        env:
          EXPO_WEB: true

      # Paso 5: Esperar a que el servidor esté listo
      - name: Wait for server to be ready
        run: |
          npx wait-on http://localhost:8081

      # Espera a que el servidor esté activo
      - name: Wait for server to be ready
        run: npx wait-on http://localhost:8081

      # Ejecuta Cypress con el comando npm run e2e
      - name: Run Cypress tests
        run: npm run e2e

      # Guarda los resultados de Cypress si hay fallas
      - name: Archive Cypress test results
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: cypress-results
          path: cypress/results