name: Run Cypress Tests on Expo Web

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.14.0'

      - name: Install dependencies
        run: |
          npm install
          npm install --save-dev cypress

      - name: Start Expo in Web Mode
        run: |
          npx expo install expo-cli
          npm start
        
      - name: Wait for Expo to Start
        run: |
          timeout 30s bash -c "until curl -s http://localhost:8081; do sleep 1; done"

      - name: Run Cypress Tests
        run: npx cypress run
        env:
          CYPRESS_baseUrl: http://localhost:8081

      - name: Upload Cypress Screenshots and Videos
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos
