name: Cypress Tests

on:
  push:
    branches:
      - '*'   
  pull_request:
    branches:
      - main   

  workflow_dispatch:

permissions:
  contents: read

jobs:
  cypress-e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.1

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.14.0'

      - name: Install dependencies
        run: npm install

      - name: Start React Native 
        run: npm start --non-interactive &
        env:
          CI: true

      - name: Wait for the app to be ready
        run: npx wait-on http://localhost:8081

      - name: Wait for the application to start
        run: |
          echo "Waiting for the application to start..."
          for i in {1..30}; do
            if curl -s http://localhost:8081 > /dev/null; then
              echo "Application is up!"
              break
            fi
            echo "Waiting..."
            sleep 1
          done

      - name: e2e cypress
        run: npx cypress run
