name: Run Jest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.14.0'  # Utiliza una versión compatible con Expo

      - name: Cache node modules
        uses: actions/cache@v2
        -

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
