name: Flujo de trabajo de pruebas de Expo con Cypress

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4.2.1

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Instalar dependencias
        run: |
          npm install
          npm install --save-dev @types/react-native expo

  run-expo-tests:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4.2.1

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.14.0'

      - name: Iniciar Expo en modo Web
        run: npx expo start --web --non-interactive &
        env:
          EXPO_USE_WEB: true

      - name: Esperar a que Expo inicie
       - name: Esperar a que Expo inicie
        run: |
          while ! curl -s http://localhost:19006; do sleep 1; done

      - name: Ejecutar pruebas de Cypress
        run: npx cypress run
        env:
          CYPRESS_baseUrl: http://localhost:8081
