name: Run Cypress Tests

# Disparadores del flujo de trabajo
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  name: Dependencies
  test:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout
        uses: actions/checkout@v4.2.1

      # Paso 2: Configurar Node.js en la versión especificada
      - name: Checkout
        uses: actions/checkout@v4.2.1

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.14.0'

      # Paso 3: Instalar dependencias del proyecto
      - name: Install dependencies
        run: |
          npm install
          npm install --save-dev cypress  # Instalar Cypress como devDependency

     