name: Flujo de trabajo de pruebas de Expo con Cypress

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4.2.1

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Instalar dependencias
        run: |
          npm install
          npm install --save-dev @types/react-native
          npm install expo

  run-expo-tests:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4.2.1

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Iniciar Expo en modo Web
        run: npx expo start 

      - name: Esperar a que Expo inicie
        run: |
          timeout 30s bash -c "until curl -s http://localhost:8081; do sleep 1; done"

      - name: Ejecutar pruebas de Cypress
        run: npx cypress run
        env:
          CYPRESS_baseUrl: http://localhost:8081
